# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet restore
  displayName: 'dotnet restore'

- script: dotnet build ./src/Gaois.QueryLogger.AspNetCore/Gaois.QueryLogger.AspNetCore.csproj --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test $(buildConfiguration)'
  inputs:
    command: test
    projects: './tests/Gaois.QueryLogger.Tests.AspNetCore/Gaois.QueryLogger.Tests.AspNetCore.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
